# Give your application a name
spring.application.name=trustpay

# Enable H2 Console to view your database in the browser at http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure the database to run in memory
spring.datasource.url=jdbc:h2:mem:trustpaydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Tell Hibernate to automatically create tables based on your Java models
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Show the SQL queries that Hibernate runs in your IntelliJ console (helpful for debugging!)
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG
